language: go

go:
  - 1.11.x

install: go build -o jikefm

os: osx

env:
  - GO111MODULE=on

before_deploy:
  - go build -o jikefm
  - tar cvzf jikefm-darwin-amd64.tgz jikefm
  - ls

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
    - "jikefm-darwin-amd64.tgz"

  skip_cleanup: true
  on:
    tags: true